name: nextjs-ecommerce # Ambiente de Desenvolvimento

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=next_db
  app:
    container_name: app
    build: 
      context: ../pc-store
      dockerfile: ../docker/Dockerfile
    ports:
      - 8000:3000
    volumes:
      - ../pc-store:/app
      # - /app/node_modules # Preserva a node_modules no container
    depends_on:
      - db