name: nextjs-ecommerce

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=next_db

  app:
    container_name: app
    build: 
      context: ../pc-store
      dockerfile: ../docker/Dockerfile
    ports:
      - 3000:8000
    volumes:
      - ../pc-store:/app
    depends_on:
      - db